<a href="https://colab.research.google.com/github/JHWannabe/Python-AI_4_2/blob/main/0124%20Day5/10_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 파이토치(Pytorch)**

* Pytorch는 tensorflow와 함께 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch임
* New York 대학교와 Facebook이 공동으로 만들었고, 가장 대중적으로 널리 사용되는 framework임

In [1]:
import torch
print(torch.__version__)

1.10.0+cu111


### **1-1. Tensor**

* 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조
* Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)함

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # 카피를 만듦(새로운 텐서, 메모리 낭비)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_1[0,0] =10
print(x_np_1)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[1 2]
 [3 4]]


In [6]:
x_np_2 = torch.as_tensor(np_array) # 뷰(참조)를 만듦(메모리 공유)
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_np_2[0,0] =10
print(x_np_2)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [8]:
x_np_3 = torch.from_numpy(np_array) # 뷰를 만듦
print(x_np_3)

tensor([[10,  2],
        [ 3,  4]])


In [9]:
x_np_3[0,0] =10
print(x_np_3)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [10]:
# 텐서 -> ndarray
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[10  2]
 [ 3  4]] <class 'numpy.ndarray'>


In [11]:
a = torch.ones(2,3)
print(a)
b = torch.zeros(2,3)
print(b)
c = torch.full((2,3), 2)
print(c)
d = torch.empty(2,3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[-4.9889e+19,  3.0966e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.0000e+00]])


In [12]:
i = torch.eye(3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
k = torch.rand(2,2)
l = torch.randn(2,2)
print(k)
print(l)

tensor([[0.7284, 0.0615],
        [0.8953, 0.9851]])
tensor([[ 0.1330,  1.3716],
        [-1.0434, -0.4784]])


### **1-2. Tensor 속성**

In [15]:
tensor = torch.rand(3,4)
print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [16]:
# 속성 변경
tensor = tensor.reshape(4,3)
tensor = tensor.int()
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
DataType of tensor : torch.int32
Device of tensor : cuda:0
