<a href="https://colab.research.google.com/github/JHWannabe/Python-AI_4_2/blob/main/0124%20Day5/9_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0%EC%99%80_%EC%BC%80%EB%9D%BC%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 텐서플로우(TensorFlow) / 케라스(Keras)**

* 텐서플로우와 케라스는 ML 모델 개발하고 학습시키는데 도움이 되는 핵심 오픈소스 라이브러리
* 케라스는 사용자가 텐서플롱루를 좀 더 쉽고 편하게 사용할 수 있게 해주는 high level API를 제공
* 텐서플로우 2.X에서는 케라스를 딥러닝의 공식 API로 채택하였고, 텐서프로우 내의 하나의 프레임워크로 개발되고 있음

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
print(tf.__version__)
print(keras.__version__)

2.7.0
2.7.0


### **1-1. Tensor**

Tensor는 multi-dimensional array를 나타내는 말로, Tensorflow의 기본 data type

In [ ]:
hello = tf.constant([3,3], dtype=tf.float32)
print(hello)

hello = tf.constant('Hello Tensor!')
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!', shape=(), dtype=string)


In [ ]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x_np = np.array([[1.0, 2.0],[3.0, 4.0]])
x_list = [[1.0, 2.0],[3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# numpy의 ndarray, python의 list를 tensor로 바꿈
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# tensor를 numpy ndarray로 바꿈
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [ ]:
# 텐서플로우의 함수(넘파이와 비슷)
a = tf.ones((2, 3))
print(a)
b = tf.zeros((2, 3))
print(b)
c = tf.fill((2,3), 2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [ ]:
# shape와 dtype을 복사
d = tf.zeros_like(c)
print(d)
e = tf.ones_like(c)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
f = tf.eye(5)
print(f)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [ ]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
h = tf.random.uniform((2, 2))
print(h)
i = tf.random.normal((2, 2))
print(i)

tf.Tensor(
[[0.6002594  0.9594364 ]
 [0.21469533 0.67822385]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.12230544  0.07383277]
 [-1.4111891  -1.0654051 ]], shape=(2, 2), dtype=float32)


### **1-2. Tensor의 속성**

In [ ]:
tensor = tf.random.normal((3, 4))
print(f'Shape : {tensor.shape}')
print(f'DataType : {tensor.dtype}')

Shape : (3, 4)
DataType : <dtype: 'float32'>


In [ ]:
# 속성 변경
tensor = tf.reshape(tensor, (4, 3))
tensor = tf.cast(tensor, tf.int32)
print(f'Shape : {tensor.shape}')
print(f'DataType : {tensor.dtype}')

Shape : (4, 3)
DataType : <dtype: 'int32'>


### **1-3. Variable**

* Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
* 딥러닝에서는 학습해야하는 가중치(weight, bias)들을 variable로 생성

In [ ]:
tensor = tf.ones((3, 4))

# tensor[0,0] = 2  --> 실행불가

In [ ]:
# variable 만들기, 값 변경
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [ ]:
initial_value = tf.random.normal(shape=(2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2.1173415 , 1.1380469 ],
       [0.37660587, 1.6956403 ]], dtype=float32)>


In [ ]:
# assign(value) : 값 설정
# assign_add(increment) : 더하기
# assign_sub(decrement) : Q빼기
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign_add(new_value)
print(weight)

added_value = tf.ones(shape=(2,2))
weight.assign_sub(added_value)
print(weight)

tf.Tensor(
[[-1.2014499   0.38530847]
 [ 1.5216831  -0.55819243]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.6655862, -1.8515513],
       [ 0.6829945, -0.7738284]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.6655862 , -2.8515513 ],
       [-0.31700552, -1.7738284 ]], dtype=float32)>


### **1-4. Indexing과 Slicing**

In [ ]:
a = tf.range(1, 13)
print(a)

a =tf.reshape(a, (3,4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
# indexing : 인덱싱을 하게되면 차원이 감소하게 됨
print(a[1])
print(a[0, -1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# slicing : 슬라이싱은 차우너이 유지됨
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### **1-5. Transpose(차원 바꾸기)**

In [ ]:
a = tf.range(16)
print(a)
a = tf.reshape(a, (2, 2, -1)) # -1은 자동으로 만들라는 뜻
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [ ]:
print(a)
# transpose(전치할 행렬, 차원의 순서, [오퍼레이션 명칭])
b = tf.transpose(a, (2, 0, 1))  # shape를 보면 (2, 2, 4) -> (4, 2, 2)
print(b)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### **1-6. Tensor 연산**

In [ ]:
x = tf.constant([[1,2], [3,4]], dtype=tf.float32)
y = tf.constant([[5,6], [7,8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [1]:
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))
print(tf.matmul(x, y))
print('*' * 50)
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

NameError: ignored

In [ ]:
z = tf.range(1, 11)
print(z)
z = tf.reshape(z, (2,5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [ ]:
# 요소의 함계
print(tf.reduce_sum(z))

tf.Tensor(55, shape=(), dtype=int32)


In [ ]:
sum1 = tf.reduce_sum(z, axis=0)
print(sum1)
sum2 = tf.reduce_sum(z, axis=1)
print(sum2)
sum3 = tf.reduce_sum(z, axis=-1)
print(sum3)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [ ]:
concat = tf.concat([z, z], axis=0)
print(concat)
concat = tf.concat([z, z], axis=1)
print(concat)
concat = tf.concat([z, z], axis=-1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
