<a href="https://colab.research.google.com/github/JHWannabe/Python-AI_4_2/blob/main/0126%20Day6/10_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 파이토치(Pytorch)**

* Pytorch는 tensorflow와 함께 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch임
* New York 대학교와 Facebook이 공동으로 만들었고, 가장 대중적으로 널리 사용되는 framework임

In [2]:
import torch
print(torch.__version__)

1.10.0+cu111


### **1-1. Tensor**

* 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조
* Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)함

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
import numpy as np

In [5]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # 카피를 만듦(새로운 텐서, 메모리 낭비)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_np_1[0,0] =10
print(x_np_1)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[1 2]
 [3 4]]


In [7]:
x_np_2 = torch.as_tensor(np_array) # 뷰(참조)를 만듦(메모리 공유)
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [8]:
x_np_2[0,0] =10
print(x_np_2)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [9]:
x_np_3 = torch.from_numpy(np_array) # 뷰를 만듦
print(x_np_3)

tensor([[10,  2],
        [ 3,  4]])


In [10]:
x_np_3[0,0] =10
print(x_np_3)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [11]:
# 텐서 -> ndarray
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[10  2]
 [ 3  4]] <class 'numpy.ndarray'>


In [12]:
a = torch.ones(2,3)
print(a)
b = torch.zeros(2,3)
print(b)
c = torch.full((2,3), 2)
print(c)
d = torch.empty(2,3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[-9.9144e-06,  3.0754e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.0000e+00]])


In [13]:
i = torch.eye(3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
k = torch.rand(2,2)
l = torch.randn(2,2)
print(k)
print(l)

tensor([[0.6273, 0.3036],
        [0.7025, 0.3625]])
tensor([[-0.3503,  0.9039],
        [ 0.7828, -0.0313]])


### **1-2. Tensor 속성**

In [16]:
tensor = torch.rand(3,4)
print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [17]:
# 속성 변경
tensor = tensor.reshape(4,3)
tensor = tensor.int()
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
DataType of tensor : torch.int32
Device of tensor : cuda:0


### **1-3. Indexing과 Slicing**

In [18]:
a = torch.arange(1, 13).reshape(3,4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [20]:
print(a[1])
print(a[0, -1])

tensor([5, 6, 7, 8])
tensor(4)


In [21]:
print(a[1:-1])

tensor([[5, 6, 7, 8]])


In [22]:
print(a[:2, 2:])

tensor([[3, 4],
        [7, 8]])


### **1-4. Transpose**

In [26]:
a = torch.arange(24).reshape(2,3,4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4])


In [27]:
b = a.transpose(1, 2)
print(b, b.shape)

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]]) torch.Size([2, 4, 3])


In [28]:
c = a.permute((2, 0, 1))
print(c, c.shape)

tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]]) torch.Size([4, 2, 3])


### **1-5. Tensor 연산**

In [29]:
x = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
y = torch.tensor([[5,6], [7,8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [31]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('*'*30)
print(torch.add(x,y))
print(torch.subtract(x,y))
print(torch.multiply(x,y))
print(torch.divide(x,y))
print(torch.matmul(x,y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [32]:
# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y)) # x에 결과를 다시 저장
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [34]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [35]:
sum1 = torch.sum(z, axis=0)
sum2 = torch.sum(z, axis=1)
sum3 = torch.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [36]:
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach()
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])


In [37]:
c = torch.cat([a,b], axis=-1)
print(c, c.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]]) torch.Size([4, 12])
